workflows:
  ios-unsigned-expo:
    name: iOS Unsigned Build (Expo)
    environment:
      node: 18
      xcode: latest
      groups:
        - test  # contains EAS_USERNAME and EAS_PASSWORD
    scripts:
      - name: Install dependencies
        working_directory: collegeapp
        script: |
          npm install -g eas-cli
          npm install
      - name: Login to EAS
        working_directory: collegeapp
        script: |
          printf "ItsHarli\ni^4k4!+.kf_3U+u\n" | eas login
      - name: Build iOS (unsigned)
        working_directory: collegeapp
        script: |
           eas build -p ios --profile preview --local
    artifacts:
      - collegeapp/dist/*.ipa
