artifacts:
      - collegeapp/dist/*.ipaworkflows:
  ios-unsigned-expo:
    name: iOS Unsigned Build (Expo)
    environment:
      node: 18
      xcode: latest
      groups:
        - test
      vars:
        EXPO_TOKEN: ZQ4gVXrR2NWdSmtNc7hugZfKLYGUf_VFwt_KGieG
    scripts:
      - name: Install dependencies
        working_directory: collegeapp
        script: |
          npm install -g eas-cli
          npm install
      - name: Check project structure
        working_directory: collegeapp
        script: |
          echo "Checking project structure..."
          ls -la
          echo "Looking for App files..."
          find . -name "App.*" -type f
          echo "Checking package.json main entry..."
          cat package.json | grep -A 5 -B 5 "main"
      - name: Login to EAS
        working_directory: collegeapp
        script: |
          export EXPO_TOKEN=ZQ4gVXrR2NWdSmtNc7hugZfKLYGUf_VFwt_KGieG
          eas whoami
      - name: Build iOS (unsigned)
        working_directory: collegeapp
        script: |
           eas build -p ios --profile preview --local --non-interactive --clear-cache
