workflows:
  ios-unsigned-expo:
    name: iOS Unsigned Build (Expo)
    environment:
      node: 18
      xcode: latest
      groups:
        - test
    scripts:
      - name: Install dependencies
        working_directory: collegeapp
        script: |
          npm install -g eas-cli
          npm install
      - name: Authenticate with Expo
        working_directory: collegeapp
        script: |
          eas whoami || eas login --token $EXPO_TOKEN
      - name: Build iOS (unsigned)
        working_directory: collegeapp
        script: |
          eas build -p ios --profile preview --non-interactive
    artifacts:
      - collegeapp/dist/*.ipa
