workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          cd YorkCollege
          flutter pub get
      - name: Build iOS .app (unsigned)
        script: |
          cd YorkCollege
          flutter build ios --no-codesign
    artifacts:
      - YorkCollege/build/ios/iphoneos/*.app
